MVC/Controllers/CustomAccount/CustomAccountController.cs
using Models.CustomAccount;
using MVC.AppCode;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers.CustomAccount
{
    public class CustomAccountController : Controller
    {
        public string APIURL
        {
            get
            {
                return ConfigurationManager.AppSettings["apiURL"].ToString();
            }
        }
        //
        // GET: /CustomAccount/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Register details)
        {
            if (ModelState.IsValid)
            {
                string apiURL =APIURL+ "api/CustomAccount/Register/";
                var result = Helper.Instance.PostToWebApi(apiURL, details);
            }
            return RedirectToAction("Index", "Home");
        }


        public ActionResult Login()
        {
            ModelState.Clear();
            return View();
        }

        [HttpPost]
        public ActionResult Login(Login model)
        {
            if (ModelState.IsValid)
            {
                string apiURL = APIURL + "api/CustomAccount/Login";
                var result = Helper.Instance.PostToWebApi(apiURL, model);
                var stringResult = JsonConvert.DeserializeObject<string>(result);
                if (stringResult != "Success")
                    ModelState.AddModelError("", stringResult);
                else
                {
                    System.Web.HttpContext.Current.Session["CurrentUser"] = model.UserName;
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }

        public ActionResult LogOff()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Manage(ManageMessageId message)
        {
            //ViewBag.StatusMessage =
               // message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
               // : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                //: message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
                //: message == ManageMessageId.Error ? "An error has occurred."
                //: "";
            //ViewBag.HasLocalPassword = HasPassword();
            //ViewBag.ReturnUrl = Url.Action("Manage");
            return RedirectToAction("Index", "Home");

        }
        private bool HasPassword()
        {
            //var user = UserManager.FindById(User.Identity.GetUserId());
            //if (user != null)
            //{
            //  return user.PasswordHash != null;
            //}
            return false;
        }
        public enum ManageMessageId
        {
            ChangePasswordSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
            Error
        }
    }
}

MVC/Views/CustomAccount/Login.cshtml
@model Models.CustomAccount.Login

@{
    ViewBag.Title = "Login";
}
<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (@Html.BeginForm("Login", "CustomAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>log-in with your account</h4>
                <hr/>
                @Html.ValidationSummary(true);@*will display below the textboxes if true else on the summary*@
                <div class="form-group">
                    @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.UserName,"", new { @class = "form-control",placeholder="user name" })
                        @Html.ValidationMessageFor(m => m.UserName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control",placeholder="password" })
                        @Html.ValidationMessageFor(m => m.Password)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <input id="Submit" type="submit" class="btn btn-default" value="Login" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register", "Register", "CustomAccount") if you do not have an account
                </p>

            }
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/Jqueryval")
}

MVC/Views/CustomAccount/Register.cshtml
@model Models.CustomAccount.Register
@{
    ViewBag.Title = "Register";
}

@using (@Html.BeginForm("Register", "CustomAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create new account</h4>
    <hr />
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", placeholder = "Enter Name" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", placeholder = "Enter Name" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmailId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmailId, new { @class = "form-control", placeholder = "Enter email id" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Enter Password" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", placeholder = "Confirm Password" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            <input type="submit" id="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}