MVC/Areas/NoOffers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Areas.NoOffers.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /NoOffers/Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

MVC/Areas/Offers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Areas.Offers.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Offers/Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

MVC/Controllers/HomeController.cs
using MVC.AppCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [CustomAuthorization("Admin")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult FirstPage(string UserName, string Password)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string UserName, string Password)
        {
            var s = UserName;
            var p = Password;
            return null;
        }
    }
}

MVC/Controllers/Shared/UserDetailsController.cs
using Models;
using MVC.AppCode;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers.Shared
{
    public class UserDetailsController : Controller
    {
        public string APIURL
        {
            get
            {
                return ConfigurationManager.AppSettings["apiURL"].ToString();
            }
        }
        //
        // GET: /UserDetails/
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult GetUserDetails()
        {
            string apiURL = APIURL + "api/UserDetails/GetUserDetails/";
            var result = Helper.Instance.GetFromWebApi(apiURL);
            List<UserDetails> userDetails = Newtonsoft.Json.JsonConvert.DeserializeObject<List<UserDetails>>(result);
            return PartialView("~/Views/Shared/_GetUserDetails.cshtml", userDetails);
        }
    }
}

MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC/Views/Home/FirstPage.cshtml
@{
    ViewBag.Title = "FirstPage";
}

<h2>FirstPage</h2>
@*@{Html.RenderPartial("_Partial");}*@

<div class="form-group">
    <div class="form-group">
        @Html.Action("GetUserDetails", "UserDetails")
    </div>
    <div class="row">
        <div class="col-md-8">
            <p>Select users from above and login</p>
            <div class="form-group">
                @Html.Label("lblUserName", "UserName", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBox("txtUserName", "", new { @class = "form-control", placeholder = "Enter Name" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("lblPassword", "Password", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBox("txtPassword", "", new { @class = "form-control", placeholder = "Enter Password" })
                </div>
            </div>
            <div class="form-group ">
                <div class="col-md-10 col-md-offset-2">
                    <input type="submit" id="submit" value="Log in" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Home/FirstPage.js"></script>

MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.ActionLink("Go to offers", "Index", "Home", new { area = "Offers" }, null)<br/>
@Html.ActionLink("Go to No Offers", "Index", "Home", new { area = "NoOffers" }, null)

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>